export const FETCH_POKEMON_LIST_PENDING = 'FETCH_POKEMON_LIST_PENDING';
export const FETCH_POKEMON_LIST_FULFILLED = 'FETCH_POKEMON_LIST_FULFILLED';
export const FETCH_POKEMON_LIST_REJECTED = 'FETCH_POKEMON_LIST_REJECTED';
