export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS';
export const GET_POKEMON_LIST_FAILED = 'GET_POKEMON_LIST_FAILED';

export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILED = 'GET_POKEMON_FAILED';
